"""empty message

Revision ID: 8aefb1a694e1
Revises: c88b69b47d6b
Create Date: 2023-07-04 15:01:48.563832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aefb1a694e1'
down_revision = 'c88b69b47d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_details',
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('fixed_cost', sa.Float(), nullable=False),
    sa.Column('variable_cost_per_km', sa.Float(), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('avg_speed_kmph', sa.Float(), nullable=False),
    sa.Column('characteristics', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fleet_details')
    # ### end Alembic commands ###
