"""empty message

Revision ID: e9be357f1ccb
Revises: 8aefb1a694e1
Create Date: 2023-07-04 15:06:00.684019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9be357f1ccb'
down_revision = '8aefb1a694e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_details',
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('order_weight', sa.Double(), nullable=False),
    sa.Column('order_volume', sa.Double(), nullable=False),
    sa.Column('delivery_slot_start_time', sa.DateTime(), nullable=False),
    sa.Column('delivery_slot_end_time', sa.DateTime(), nullable=False),
    sa.Column('special_vehicle_requirements', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_availability',
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('availability_start_time', sa.DateTime(), nullable=False),
    sa.Column('availability_end_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_availability')
    op.drop_table('order_details')
    # ### end Alembic commands ###
